### ISSUE TITLE
Cannot demultiplex large number of barcode combinations

### ISSUE THREAD

**Issue by martinclausen2** [MikkelSchubert/adapterremoval#29] opened 2018-11-26 19:52 UTC
Hi Mikkel,

Thanks for the nice project!
I have almost 5000 barcode combinations (system with fwd and rev barcodes). adapterremoval unfortunately is not able to handle such a high number of files to be open in parallel.
Could this be improved?

Greetings,
Martin

**Comment by MikkelSchubert** [comment] 2018-11-28 11:15
Hi Martin,

I am glad to hear that you like AdapterRemoval.

It should certainly be possible to improve this situation, though there
will no doubt be some cost having to open/close files on demand.
I will try to give it a shot one of the next few days and see what I can do.

Best,
 Mikkel

**Comment by martinclausen2** [comment] 2018-11-28 19:21
Hi Mikkel,

thanks for your quick response! Maybe a simple solution would be to take he first bunch of barcode pairs, process them take remainder of sequences and barcodes and repeat the procedure until everything is processed. This would keep up the speed for short list and enable longer barcode lists at the same time.

Best,
Mikkel

**Comment by MikkelSchubert** [comment] 2019-02-10 17:07
Hey Martin,

I apologize for taking so long.
I've been exploring a number of options, and have now added an solution that should hopefully fix this problem, by dynamically closing and re-opening files as required, when there are too many files in use. It still needs some testing, but it should hopefully solve this problem without requiring user intervention.

However, my testing also revealed poor performance when using a very large number of barcodes, so I have also been working on improving that situation as well. I hope to release a new version of AdapterRemoval that addresses both of these issues before too long.

Best,
 Mikkel

**Comment by martinclausen2** [comment] 2019-02-11 19:27
Hi Mikkel,

that would be great, the problem is still pending on our side. Performance is not so much an issue for us. I look forward to test a new version!

Best,
Martin

**Comment by kalen-rasmussen** [comment] 2019-02-26 20:19
Hey Mikkel,

I have come across the same issue, and based upon messing around with the number of barcodes, I could only get AdapterRemoval to demultiplex 96 samples at a time. Not sure if that is helpful, but that seems to be the max'ish number right not. 

Also, side question. Is there a way to  completely avoid adding a basename to the output files? i.e. no "your_output" or user specified prefix at all? 

Thanks,
-K

**Comment by MikkelSchubert** [comment] 2019-03-03 18:47
Hi Martin and Kalen-Rasmussen,

The limit you (Kalen) are running into is based on your ulimit (see 'ulimit -a'). The exact number will depend on your system settings, and can be increased if you have root access. For shared system, you will need to contact your administrator. In my experience, these are not always willing to increase your limits, which is why I've been working on a solution that does not depend on having root access.


I've committed a preliminary version of AdapterRemoval that is able to work around this (by closing and re-opening files on demand). This version also includes a reworking of the demultiplexing system, to improve performance for paired barcodes. 

I'm aiming to release an offical version sometime next week, once I am satisfied that everything works as intended, but you can download and test it now if you download the current development version:
https://github.com/MikkelSchubert/adapterremoval/archive/master.zip


I've also made it possible to avoid having a basename for your output files. This is done simply by specifying an empty basename (--basename "") or by using a basename that ends with a slash (--basename /path/to/output/). If you do so, you'll get files like 'settings' instead of 'basename.settings'.

Best regards,
 Mikkel

**Comment by MikkelSchubert** [comment] 2019-03-12 17:08
I've released AdapterRemoval v2.3.0 which includes both support for limited file handles as well as output files without basenames. Please let me know if you run into any issues and thank you for your patience.

Cheers,
 Mikkel

**Closed by MikkelSchubert** 2019-03-12 17:08 UTC

**Comment by kalen-rasmussen** [comment] 2019-03-12 17:24
Great and thank you for all the hard work!

-K
