### ISSUE TITLE
Invalid fastq files produced

### ISSUE THREAD

**Issue by habibr** [MikkelSchubert/adapterremoval#7] opened 2016-03-16 05:52 UTC
Hi,
I used AdapterRemoval recently and found out that sometimes it produced invalid fastq files like this:

@ST-E00114:418:HHKV7CCXX:8:1109:26484:40020 2:N:0:GCCAAT
TTCAAGAGGTCTTAAGGAGGCTAACTCATATATAGGTTAGGTCTAGATCTAGAGGATGAGAGCATGGGAGACATGGATGTACATAGACTCGATAAGTACTT
+
AA<F<FAFAA<,FFKKK<FFFKKKKKKKKKKKFKKKAFFF79:40020 2:N:0:GCCAAT

As shown, the quality line is truncated and merged with a segment of the header line. There are four copies of those lines which may be due to the 4 threads that I specified to the program.

This was complained by bowtie2 that saw "a space" in the quality line.

**Comment by MikkelSchubert** [comment] 2016-03-16 12:01
Thanks for letting me know about this problem!
Could you tell me version of AdapterRemoval you used (run 'AdapterRemoval --version' if in doubt), as well as all parameters that you used?

Cheers

**Comment by habibr** [comment] 2016-03-18 03:41
I was using AdapterRemoval ver. 2.1.5
It was run on a VirtualBox Ubuntu 15,10 machine with 3Gb memory allocation with the following parameters: 
AdapterRemoval --file1 Aren_1.fastq.gz --file2 Aren_2.fastq.gz --basename Aren_qc --trimns --trimqualities --collapse --qualitymax 42 --adapter1 AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC --adapter2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT --threads 4 --gzip --mate-separator " " &

**Comment by MikkelSchubert** [comment] 2019-10-12 20:13
I am closing this issue as I have been unable to reproduce this bug and as I have received no further reports of this problem. Thank you again for letting me know and please do not hesitate to report other any issues.

Best,
 Mikkel

**Closed by MikkelSchubert** 2019-10-12 20:13 UTC
