### ISSUE TITLE
Test suite fails in i386 architecture with strange replacement of "(" by "'"

### ISSUE THREAD

**Issue by tillea** [MikkelSchubert/adapterremoval#35] opened 2019-03-05 10:21 UTC
Hi,
there is a [Debian bug report](https://bugs.debian.org/923772)  about test failures which strangely fail only on i386 and the error itself is pretty strange:

    tests/unit/alignment_test.cpp:841: FAILED:
      REQUIRE( collapsed_result == collapsed_expected )
    with expansion:
      '@Rec1\nGCATGATATATACAAC\n+\n012345'FBcEFGHIJ\n'
      ==
      '@Rec1\nGCATGATATATACAAC\n+\n012345(FBcEFGHIJ\n'

(just see the separating sign after 012345 - the diff is not easily to spot).  This occures out of lots of Debian architectures where the package builds nicely only for i386 (I can not exclude that the specific autobuilder might have different language settings or so).  The [full build log](https://buildd.debian.org/status/fetch.php?pkg=adapterremoval&arch=i386&ver=2.2.4-1&stamp=1550748158&raw=0) is available as well.
Kind regards, Andreas.

**Comment by MikkelSchubert** [comment] 2019-03-10 15:56
Thank you for letting me know.

It looks like this is caused by std::log10 giving very slightly different results on i386, so I'll probably just hardcode the lookup table to ensure that results are reproducible across the two architectures.

Best,
 Mikkel

**Comment by tillea** [comment] 2019-03-12 10:15
Hi Mikkel,

On Sun, Mar 10, 2019 at 08:56:04AM -0700, Mikkel Schubert wrote:
> It looks like this is caused by std::log10 giving very slightly different results on i386, so I'll probably just hardcode the lookup table to ensure that results are reproducible across the two architectures.
You surely know your code better than I but for me its extremely strange that while the numbers are actally equal only the sepraters between the numbers are different.  Your explanation would rather imply that the numbers itself would be different.  But may be those different separators have a certain meaning I'd be unaware about.

**Comment by MikkelSchubert** [comment] 2019-03-12 10:43
Hi Andreas,

You're looking at a comparison between two FASTQ reads:

    @Rec1
    GCATGATATATACAAC
    +
    012345'FBcEFGHIJ

and

    @Rec1
    GCATGATATATACAAC
    +
    012345(FBcEFGHIJ


The format is roughly
  
    @[name]
    [N * Nucleotides]
    +
    [N * Phred quality scores]


So the difference is that the quality score for the 7th base (a 'T') is "'" instead of "(", corresponding to a Phred quality score of 6 instead of 7 (calculated as ASCII value - 33). It is merely a coincidence that this happened between numerical and non-numerical values.

During the collapse step, in which two overlapping reads are merged, updated quality scores are calculated as a product of the scores for the two copies of the overlapping base-pair. This will either result in a higher quality score being assigned (for identical positions) or a lower quality score being assigned (for mismatching positions). 

The calculation to determine the updated quality score makes use of std::log10, which appears to produce slightly different results on i386 vs amd64, resulting in a small number of updated quality scores being off by one on i386 compared to amd64. I determined this simply by printing every single intermediate result for this calculation for binaries built with and without -m32.

The solution I am taking is to simply pre-calculate the lookup table and include a hardcoded copy of that, instead populating the table when it is first used. It is not the prettiest solution, but it ensures that results can be reproduced regardless of the architecture.

I realize that my last comment was rather vague, but I hope that this makes it clear what the issue was.

See https://en.wikipedia.org/wiki/FASTQ_format for a detailed description of the format.

**Comment by tillea** [comment] 2019-03-12 14:40
Hi Mikkel, thanks a lot for the verbose explanation.  Are you able to predict some time when you will be able to fix this situation?  I do not want to put pressure but Debian is currently in Freeze.  So if you are not able to fix this in the next 2-3 weeks I'd rather simply remove the package for i386 (which is probably no big constraint in practical cases).  Otherwise the whole package would be removed for all architectures which is way worse.  Just let me know what you think to let me draw some senisible decision, Andreas.

**Comment by MikkelSchubert** [comment] 2019-03-12 17:09
I predict that I'll release a new version of AdapterRemoval 5 minutes ago. ;)

**Closed** 2019-08-05 12:19 UTC
